Update kaltura-batch
Resolve issue with batch throwing an incorrect error and correctly recognize the parent ID.

diff --git a/RPM/SOURCES/kaltura-batch b/RPM/SOURCES/kaltura-batch
--- a/RPM/SOURCES/kaltura-batch
+++ b/RPM/SOURCES/kaltura-batch
@@ -19,9 +19,8 @@
 
 
 # Source function library.
-#. /etc/rc.d/init.d/functions
-
 . /etc/kaltura.d/system.ini
+
 # Directory containing the batchers' php files
 BATCHDIR=$APP_DIR/batch
 
@@ -36,26 +35,18 @@ CONFIG_FILE=$APP_DIR/configurations/batch
 
 LOCKFILE="$LOG_DIR/batch/batch.pid"
 
-echo_success() {
-	[ "$BOOTUP" = "color" ] && $MOVE_TO_COL
-	echo -n "["
-	[ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
-	echo -n $"	OK	"
-	[ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-	echo -n "]"
-	echo -ne "\r"
-	return 0
-}
-
-echo_failure() {
-	[ "$BOOTUP" = "color" ] && $MOVE_TO_COL
-	echo -n "["
-	[ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-	echo -n $"FAILED"
-	[ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-	echo -n "]"
-	echo -ne "\r"
-	return 1 
+echo_status() {
+    RED=$(tput setaf 1)
+    GREEN=$(tput setaf 2)
+    NORMAL=$(tput sgr0)
+    MSG="$1"
+    if [ $2 -eq 0 ]; then
+        let COL=$(tput cols)-${#MSG}+${#GREEN}+${#NORMAL}
+        printf "%s%${COL}s" "$MSG" "$GREEN[    OK    ]$NORMAL"
+    else
+        let COL=$(tput cols)-${#MSG}+${#RED}+${#NORMAL}
+        printf "%s%${COL}s" "$MSG" "$RED[  FAILED  ]$NORMAL"
+    fi
 }
 
 
@@ -65,79 +56,79 @@ start() {
 		return 1
 	fi
 	
-	echo -n $"Starting:"
-	KP_PARENT=`cat $LOCKFILE 2>/dev/null`
-	KP=`ps axf | awk '!/\\_ / {b=0} /php [K]GenericBatchMgr.class.php/ {b=1} b{print $1}'|xargs`
-	if ! `kill -0 "$KP_PARENT" 2>/dev/null` 2>/dev/null; then
-		echo_failure
-		echo
-		if [ "X$KP_PARENT" != "X" ]; then
-			echo "Service batch already running [$KP_PARENT]"
+    KP=`ps axf | awk '!/\\_ / {b=0} /php [K]GenericBatchMgr.class.php/ {b=1} b{print $1}'|xargs`
+    if [ -f "$LOCKFILE" ]; then
+        KP_PARENT=`cat $LOCKFILE 2>/dev/null`
+        kill -0 $KP_PARENT
+        if [ $? -eq 0 ]; then
+			echo "Service Batch Manager already running [$KP_PARENT]"
 			return 0
-		else
-			echo "Service batch isn't running but stale lock file exists"
-			echo "Removing stale lock file at $LOCKFILE"
-			rm -f $LOCKFILE
-			start_scheduler
-			return 0 
-		fi
-	else
-		if [ "X$KP" != "X" ]; then
-			echo "Batch is running as $KP without a $LOCKFILE"
-			return 0
-		fi		
+        else
+            echo "Service Batch Manager isn't running but stale lock file exists"
+            echo "Removing stale lock file $LOCKFILE"
+            rm -f $LOCKFILE
+            start_scheduler
+            return 1
+        fi
+	elif [ -n "$KP" ]; then
+        echo "Batch Manager is running as $KP without $LOCKFILE"
 		start_scheduler
 		return 0
+    else
+        start_scheduler
+        return 1
 	fi
 }
 
 start_scheduler() {
-	echo "$PHP_BIN $BATCHEXE $PHP_BIN $CONFIG_FILE >> $LOG_DIR/kaltura_batch.log 2>&1 &"
+    echo -n "Starting Batch Manager."
 	cd $BATCHDIR
-	su $OS_KALTURA_USER -c "nohup $PHP_BIN $BATCHEXE $PHP_BIN $CONFIG_FILE >> $LOG_DIR/kaltura_batch.log 2>&1 &" 
+    echo -n "."
+	su $OS_KALTURA_USER -c "nohup $PHP_BIN $BATCHEXE $PHP_BIN $CONFIG_FILE >> $LOG_DIR/kaltura_batch.log 2>&1 &"
+    echo -n "."
 	if [ "$?" -eq 0 ]; then
-		echo_success
-		echo
+        echo ". "
+        sleep 1
+        KP_PARENT=`cat $LOCKFILE 2>/dev/null`
+        echo_status "Batch Manager started with PID $KP_PARENT" 0
+        return 0
 	else
-		echo_failure
-		echo
+        echo ". "
+        echo_status "Failed to start Batch Manager" 1
+        return 1
 	fi
 }
 
 show_status() {
-		KP=`ps axf | awk '!/\\_ / {b=0} /php [K]GenericBatchMgr.class.php/ {b=1} b{print $1}'|xargs`
-		if [ -n "$KP" ]; then
-		echo "Batch is running as $KP ..."
-		return 0
-		else
-			echo "Service Batch isn't running"
-			return 1 
-		fi
+    KP=`ps axf | awk '!/\\_ / {b=0} /php [K]GenericBatchMgr.class.php/ {b=1} b{print $1}'|xargs`
+    KP_PARENT=`cat $LOCKFILE 2>/dev/null`
+    if [ -n "$KP" ]; then
+        echo_status "Batch Manager running with PID $KP_PARENT" 0
+        return 0
+    else
+        echo_status "Service Batch Manager isn't running" 1
+        return 1 
+    fi
 }
 
 stop() {
-	echo -n $"Shutting down:"
 	KP_PARENT=`cat $LOCKFILE 2>/dev/null`
 	KP=`ps axf | awk '!/\\_ / {b=0} /php [K]GenericBatchMgr.class.php/ {b=1} b{print $1}'|xargs`
 	if [ -n "$KP" ]; then
 		if [ -f $BASE_DIR/keepAlive ]; then
 			echo "Server is on Keep Alive mode - workers won't be killed!"
-			kill -9 $KP_PARENT
+            echo_status "Killing Batch Manager with PID $KP_PARENT" 0
+			kill $1 $KP_PARENT
 		else
-			echo "Killing batchMgr and workers"
-			kill -9 $KP
+			echo_status "Killing Batch Manager with PID $KP_PARENT and related workers" 0
+			kill $1 $KP
 		fi
-		echo_success
+        rm $LOCKFILE
 		RC=$?
-		echo
 	else
-		echo_failure
-		echo
-		echo "Service Batch not running"
-		#RC=2
-		RC=0
+		echo_status "Service Batch Manager not running" 1
+		RC=1
 	fi
-	rm -f $LOCKFILE
 	return $RC
 }
 
@@ -148,6 +139,9 @@ case "$1" in
 	stop)
 		stop
 		;;
+    force-stop)
+        stop -9
+        ;;
 	status)
 		show_status
 		;;
@@ -156,7 +150,8 @@ case "$1" in
 		start
 		;;
 	*)
-		echo "Usage: [start|stop|restart|status]"
+		echo "Usage: [start|stop|force-stop|restart|status]"
 		exit 0
 		;;
 esac
+exit $?
