configure phase passes successfully. - added 'kaltura' user and group - adjusted templates

diff --git a/deb/kaltura-base/debian/postinst b/deb/kaltura-base/debian/postinst
--- a/deb/kaltura-base/debian/postinst
+++ b/deb/kaltura-base/debian/postinst
@@ -1,4 +1,4 @@
-#!/bin/sh 
+#!/bin/bash
 
 KALTURA_FUNCTIONS_RC=/opt/kaltura/bin/kaltura-functions.rc
 if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
@@ -7,7 +7,7 @@ if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
         exit 3
 fi
 . $KALTURA_FUNCTIONS_RC
-
+APP_DIR=/opt/kaltura/app
 set -e
 if [ $1 = configure ]; then
 	. /usr/share/debconf/confmodule
@@ -90,23 +90,23 @@ if [ $1 = configure ]; then
 	db_get 'kaltura-base/admin_console_passwd'
 	ADMIN_CONSOLE_PASSWORD=$RET
 
-	if echo $ADMIN_CONSOLE_PASSWORD | grep -q "/" ;then
-		echo -en "${BRIGHT_RED}ERROR: Passwd can't have the '/' char in it. Please re-input.${NORMAL}"
-		unset ADMIN_CONSOLE_PASSWORD
-	fi
-
-	if [ "$ADMIN_CONSOLE_PASSWORD" != "$AGAIN_ADMIN_CONSOLE_PASSWORD" ];then
-		echo -en "${BRIGHT_RED}ERROR: Passwds do not match, again please.${NORMAL}" 
-		unset AGAIN_ADMIN_CONSOLE_PASSWORD
-		echo -en "${BRIGHT_RED}ERROR: Admin user login password (must be minimum 8 chars and include at least one of each: upper-case, lower-case, number and a special character): ${NORMAL}"
-		read -s ADMIN_CONSOLE_PASSWORD
-	fi
-
 
 	db_input critical 'kaltura-base/admin_console_passwd_again' || true
 	db_go || true
 	db_get 'kaltura-base/admin_console_passwd_again'
 	AGAIN_ADMIN_CONSOLE_PASSWORD=$RET
+
+	#if echo $ADMIN_CONSOLE_PASSWORD | grep -q "/" ;then
+	#	echo -en "${BRIGHT_RED}ERROR: Passwd can't have the '/' char in it. Please re-input.${NORMAL}"
+	#	unset ADMIN_CONSOLE_PASSWORD
+	#fi
+
+	#if [ "$ADMIN_CONSOLE_PASSWORD" != "$AGAIN_ADMIN_CONSOLE_PASSWORD" ];then
+	#	echo -en "${BRIGHT_RED}ERROR: Passwds do not match, again please.${NORMAL}" 
+	#	unset AGAIN_ADMIN_CONSOLE_PASSWORD
+	#	echo -en "${BRIGHT_RED}ERROR: Admin user login password (must be minimum 8 chars and include at least one of each: upper-case, lower-case, number and a special character): ${NORMAL}"
+	#fi
+
 
 	db_input critical 'kaltura-base/time_zone' || true
 	db_go || true
@@ -150,13 +150,13 @@ if [ $1 = configure ]; then
 			sed -i "s#\(date.timezone\)\s*=.*#\1='$TIME_ZONE'#g" $INI
 		fi
 	done
-	if [ -z "$DB1_PASS" ];then
-		DB1_PASS=`< /dev/urandom tr -dc A-Za-z0-9 | head -c15`
-		echo "update mysql.user set password=PASSWORD('$DB1_PASS') WHERE user='kaltura';flush PRIVILEGES" | mysql -h$DB1_HOST -P$DB1_PORT -u$SUPER_USER -p$SUPER_USER_PASSWD mysql
-		if [ -z "$DWH_PASS" ];then
-			DWH_PASS=$DB1_PASS
-		fi
-	fi
+	#if [ -z "$DB1_PASS" ];then
+	#	DB1_PASS=`< /dev/urandom tr -dc A-Za-z0-9 | head -c15`
+	#	echo "update mysql.user set password=PASSWORD('$DB1_PASS') WHERE user='kaltura';flush PRIVILEGES" | mysql -h$DB1_HOST -P$DB1_PORT -u$SUPER_USER -p$SUPER_USER_PASSWD mysql
+	#	if [ -z "$DWH_PASS" ];then
+	#		DWH_PASS=$DB1_PASS
+	#	fi
+	#fi
 	DB1_NAME=kaltura
 	DB1_USER=kaltura
 
@@ -175,8 +175,6 @@ if [ $1 = configure ]; then
 		CONF_FILES="$CONF_FILES `find $BASE_DIR/dwh  -type f -name "*template*"`"
 	fi
 
-	HTML5_VER="`rpm -qa kaltura-html5lib --queryformat %{version}`"
-	create_answer_file $POST_INST_MAIL_TMPL
 	# Now we will sed.
 
 	for TMPL_CONF_FILE in $CONF_FILES;do
@@ -190,12 +188,27 @@ if [ $1 = configure ]; then
 		sed  -e "s#@ENVIRONMENT_PROTOCOL@#$PROTOCOL#g" -e "s#@CDN_HOST@#$CDN_HOST#g" -e "s#@DB[1-9]_HOST@#$DB1_HOST#g" -e "s#@DB[1-9]_NAME@#$DB1_NAME#g" -e "s#@DB[1-9]_USER@#$DB1_USER#g" -e "s#@DB[1-9]_PASS@#$DB1_PASS#g" -e "s#@DB[1-9]_PORT@#$DB1_PORT#g" -e "s#@TIME_ZONE@#$TIME_ZONE#g" -e "s#@KALTURA_FULL_VIRTUAL_HOST_NAME@#$KALTURA_FULL_VIRTUAL_HOST_NAME#g" -e "s#@KALTURA_VIRTUAL_HOST_NAME@#$KALTURA_VIRTUAL_HOST_NAME#g" -e "s#@SERVICE_URL@#$SERVICE_URL#g" -e "s#@WWW_HOST@#$KALTURA_FULL_VIRTUAL_HOST_NAME#g" -e "s#@SPHINX_DB_NAME@#kaltura_sphinx_log#g" -e "s#@SPHINX_DB_HOST@#$SPHINX_DB_HOST#g" -e "s#@SPHINX_DB_PORT@#$DB1_PORT#g" -e "s#@DWH_HOST@#$DWH_HOST#g" -e "s#@DWH_PORT@#$DWH_PORT#g" -e "s#@SPHINX_SERVER1@#$SPHINX_SERVER1#g" -e "s#@SPHINX_SERVER2@#$SPHINX_SERVER2#g" -e "s#@DWH_DATABASE_NAME@#kalturadw#g" -e "s#@DWH_USER@#etl#g" -e "s#@DWH_PASS@#$DWH_PASS#g" -e "s#@ADMIN_CONSOLE_ADMIN_MAIL@#$ADMIN_CONSOLE_ADMIN_MAIL#g" -e "s#@WEB_DIR@#$BASE_DIR/web#g" -e "s#@LOG_DIR@#$BASE_DIR/log#g" -e "s#$BASE_DIR/app#$BASE_DIR/app#g" -e "s#@PHP_BIN@#/usr/bin/php#g" -e "s#@OS_KALTURA_USER@#kaltura#g" -e "s#@BASE_DIR@#$BASE_DIR#" -e "s#@APP_DIR@#$BASE_DIR/app#g" -e "s#@DWH_DIR@#$BASE_DIR/dwh#g" -e "s#@EVENTS_LOGS_DIR@#$BASE_DIR/web/logs#g" -e "s#@TMP_DIR@#$BASE_DIR/tmp#g" -e "s#@APACHE_SERVICE@#httpd#g" -e "s#@KALTURA_VIRTUAL_HOST_PORT@#$KALTURA_VIRTUAL_HOST_PORT#g" -e "s#@BIN_DIR@#$BASE_DIR/bin#g" -e "s#@KALTURA_VERSION@#$DISPLAY_NAME#g" -e "s#@SPHINX_SERVER@#$SPHINX_SERVER#g" -e "s#@IMAGE_MAGICK_BIN_DIR@#/usr/bin#g" -e "s#@CURL_BIN_DIR@#/usr/bin#g" -e "s@^\(bin_path_mediainfo\).*@\1=/usr/bin/mediainfo@g" -e "s#@CONTACT_URL@#$CONTACT_URL#g" -e "s#@ENVIRONMENT_NAME@#$ENVIRONMENT_NAME#g" -e "s#@BEGINNERS_TUTORIAL_URL@#$BEGINNERS_TUTORIAL_URL#g" -e "s#@BEGINNERS_TUTORIAL_URL@#$BEGINNERS_TUTORIAL_URL#g" -e "s#@QUICK_START_GUIDE_URL@#$QUICK_START_GUIDE_URL#g" -e "s#@FORUMS_URLS@#$FORUMS_URLS#g" -e "s#@CONTACT_PHONE_NUMBER@#$CONTACT_PHONE_NUMBER#g" -e "s#@UNSUBSCRIBE_EMAIL_URL@#$SERVICE_URL/index.php/extwidget/blockMail?e=#g" -e "s#@UICONF_TAB_ACCESS@#SYSTEM_ADMIN_BATCH_CONTROL#g"  -e "s#@EVENTS_FETCH_METHOD@#local#g" -e "s#@HTML5_VER@#$HTML5_VER#g" -e "s#@MONIT_PASSWD@#$DB1_PASS#g" -i $CONF_FILE
 	done
 
-	sed -i "s#@MONIT_PASSWD@#$DB1_PASS#" -i $BASE_DIR/app/admin_console/views/scripts/index/monit.phtml
+KALTURA_GROUP=kaltura
+KALTURA_USER=kaltura
+APACHE_USER=www-data
+KALTURA_PREFIX=/opt/kaltura
+if ! getent group $KALTURA_GROUP >/dev/null; then
+        addgroup --system --force-badname --quiet $KALTURA_GROUP --gid 7373 
+fi
+
+if ! getent passwd $KALTURA_USER >/dev/null; then
+        adduser --system --force-badname --quiet \
+            --home $KALTURA_PREFIX --no-create-home \
+            --shell /bin/bash \
+    --uid 7373 \
+            --group $KALTURA_GROUP
+        usermod -c "Kaltura server" $KALTURA_USER
+fi
+
+
 	# these two have passwds in them.
-	chown kaltura.apache $BASE_DIR/app/configurations/system.ini $BASE_DIR/app/configurations/db.ini
+	chown kaltura.www-data $BASE_DIR/app/configurations/system.ini $BASE_DIR/app/configurations/db.ini
 	chmod 640 $BASE_DIR/app/configurations/system.ini $BASE_DIR/app/configurations/db.ini
-	chown root.root $BASE_DIR/app/configurations/monit/monit.conf
-	chmod 600 $BASE_DIR/app/configurations/monit/monit.conf
 
 
 	# gen secrets
@@ -302,7 +315,7 @@ if [ $1 = configure ]; then
 
 	find $BASE_DIR/app/cache/ $BASE_DIR/log -type d -exec chmod 775 {} \; 
 	find $BASE_DIR/app/cache/ $BASE_DIR/log -type f -exec chmod 664 {} \; 
-	chown -R kaltura.apache $BASE_DIR/app/cache/ $BASE_DIR/log
+	chown -R kaltura.www-data $BASE_DIR/app/cache/ $BASE_DIR/log
 	chmod 775 $BASE_DIR/web/content
 	if [ -d /usr/lib/red5/webapps/oflaDemo ];then
 		ln -sf $BASE_DIR/web/content/webcam /usr/lib/red5/webapps/oflaDemo/streams
