.

diff --git a/deb/kaltura-db/debian/postinst b/deb/kaltura-db/debian/postinst
--- a/deb/kaltura-db/debian/postinst
+++ b/deb/kaltura-db/debian/postinst
@@ -15,12 +15,6 @@
 #===============================================================================
 #set -o nounset                              # Treat unset variables as an error
 
-KALTURA_FUNCTIONS_RC=`dirname $0`/kaltura-functions.rc
-if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
-	echo "Could not find $KALTURA_FUNCTIONS_RC so, exiting.."
-	exit 3
-fi
-. $KALTURA_FUNCTIONS_RC
 if [ "$1" = "configure" ]; then
 	. /usr/share/debconf/confmodule
 	RC_FILE=/etc/kaltura.d/system.ini
@@ -29,18 +23,18 @@ if [ "$1" = "configure" ]; then
 		exit 2
 	fi
 	. $RC_FILE
-	DB_ACTIONS_RC=`dirname $0`/db_actions.rc
+	KALTURA_FUNCTIONS_RC=$BASE_DIR/bin/kaltura-functions.rc
+	if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
+		echo "Could not find $KALTURA_FUNCTIONS_RC so, exiting.."
+		exit 3
+	fi
+	. $KALTURA_FUNCTIONS_RC
+	DB_ACTIONS_RC=$BASE_DIR/bin/db_actions.rc
 	if [ ! -r "$DB_ACTIONS_RC" ];then
 		echo -e "${BRIGHT_RED}ERROR: could not find $DB_ACTIONS_RC so, exiting..${NORMAL}"
 		exit 3
 	fi
 	. $DB_ACTIONS_RC
-	KALTURA_FUNCTIONS_RC=`dirname $0`/kaltura-functions.rc
-	if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
-		echo -e "${BRIGHT_RED}ERROR: could not find $KALTURA_FUNCTIONS_RC so, exiting..${NORMAL}"
-		exit 3
-	fi
-	. $KALTURA_FUNCTIONS_RC
 	db_get 'kaltura-base/db_hostname'
 	DB1_HOST=$RET
 	if [ -z "$DB1_HOST" ];then
@@ -83,23 +77,13 @@ if [ "$1" = "configure" ]; then
 	# check DB connectivity:
 	echo -e "${CYAN}Checking MySQL version..${NORMAL}"
 	MYVER=`echo "select version();" | mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT -N`
-	MYMAJVER=`echo $MYVER| awk -F "." '{print $1}'`
-	MYMINORVER=`echo $MYVER| awk -F "." '{print $2}'`
-
-	if [ "$MYMAJVER" -ne 5 ];then
-		echo -e "${BRIGHT_RED}Your version of MySQL is not compatible with Kaltura at the moment. 
-	Please install and configure MySQL 5.1 according to the instructions on the Kaltura install manual before proceeding with the Kaltura installation.${NORMAL}"
-		exit 1
-	else
-		echo -e "${CYAN}Ver $MYVER found compatible${NORMAL}"
-	fi
 
 	if [ $? -ne 0 ];then
-	cat << EOF
-	Failed to run:
-	# mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT."
-	Check your settings."
-	EOF
+cat << EOF
+Failed to run:
+# mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT."
+Check your settings and run dpkg-reconfigure kaltura-db."
+EOF
 		exit 4
 	fi
 	if ! check_mysql_settings $MYSQL_SUPER_USER $MYSQL_SUPER_USER_PASSWD $MYSQL_HOST $MYSQL_PORT ;then
@@ -121,15 +105,15 @@ if [ "$1" = "configure" ]; then
 		# check whether the 'kaltura' already exists:
 		echo "use kaltura" | mysql -h$MYSQL_HOST -u$MYSQL_SUPER_USER -p$MYSQL_SUPER_USER_PASSWD -P$MYSQL_PORT $KALTURA_DB 2> /dev/null
 		if [ $? -eq 0 ];then
-	cat << EOF
-	The $KALTURA_DB DB seems to already be installed.
+cat << EOF
+The $KALTURA_DB DB seems to already be installed.
 
-	if you meant to perform an upgrade? run with:
-	# $0 $MYSQL_HOST $MYSQL_SUPER_USER $MYSQL_SUPER_USER_PASSWD $MYSQL_PORT upgrade
+if you meant to perform an upgrade? run with:
+# $0 $MYSQL_HOST $MYSQL_SUPER_USER $MYSQL_SUPER_USER_PASSWD $MYSQL_PORT upgrade
 
-	Otherwise, do you wish to remove the existing DB [n/Y]?
+Otherwise, do you wish to remove the existing DB [n/Y]?
 
-	EOF
+EOF
 			read REMOVE
 			if [ $REMOVE = "Y" ];then
 				`dirname $0`/kaltura-drop-db.sh
@@ -172,11 +156,11 @@ if [ "$1" = "configure" ]; then
 	echo "Checking connectivity to needed daemons..."
 	if ! check_connectivity $DB1_USER $DB1_PASS $DB1_HOST $DB1_PORT $SPHINX_HOST $SERVICE_URL;then
 		echo -e "${BRIGHT_RED}Please check your setup and then run $0 again.${NORMAL}"
-	cat << EOF
+cat << EOF
 
-	Do you wish to remove the existing DB or keep for debugging puropses [n/Y]?
+Do you wish to remove the existing DB or keep for debugging puropses [n/Y]?
 
-	EOF
+EOF
 		read REMOVE
 		if [ $REMOVE = "Y" ];then
 			`dirname $0`/kaltura-drop-db.sh
@@ -196,10 +180,10 @@ if [ "$1" = "configure" ]; then
 	echo -e "${CYAN}Output for $APP_DIR/deployment/base/scripts/insertContent.php being logged into $LOG_DIR/insertContent.log ${NORMAL}"
 	php $APP_DIR/deployment/base/scripts/insertContent.php >> $LOG_DIR/insertContent.log  2>&1
 	if [ $? -ne 0 ];then
-	cat << EOF
-	Failed to run:
-	php $APP_DIR/deployment/base/scripts/insertContent.php >> $LOG_DIR/insertContent.log  2>&1
-	EOF
+cat << EOF
+Failed to run:
+php $APP_DIR/deployment/base/scripts/insertContent.php >> $LOG_DIR/insertContent.log  2>&1
+EOF
 		echo -e "${BRIGHT_RED}Please check your setup and then run $0 again.${NORMAL}"
 		exit 8
 	fi
